CraftsmenLtd/BloodConnect

.githooks/commit-msg, README.md
Fixes #8 
Git commit message hook added to add issue number to commit messages.
- This script requires the git hook directory to be changed to `.githooks` directory. Keeping the default `.git/hooks` directory as hook for git will require this hook (and any future git hooks) to be added to the directory manually, as git does not manage the contents inside `.git`.
The instructions of doing so, and making the `.githooks` executable can be found in [README.md](https://github.com/CraftsmenLtd/BloodConnect/pull/18/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5).
- Make a dummy file, add to git and commit:
- without adding any issue number at the beginning of the message. Commit should fail.
- add the issue number in the following format: `I#${issueNumber} …
=> Add commit message hook

.githooks/commit-msg
Fixes #8
Resolves #
The previous `I#${issue_number} ${commit_message}` format was not tagging the issue, so refactored it to `I-#${issue_number} ${commit_message}` 
Please assess risk & follow up on deployment of …
=>  Refactor/#8 Commit Template Update

.github/workflows/deploy-docs.yml, docs/README.md
Fixes #9 
Takes the markdown files in the `docs` folder and deploys them to github pages in the link https://craftsmenltd.github.io/BloodConnect .
ar description of the problem or feature being addressed.
The current implementation adds a github action that triggers when a commit is pushed to the current branch (issue-9-doc-as-readable-site). If the action needs to be triggered with any other branch, the branch needs to be added to the environment from settings (https://github.com/withastro/docs/issues/1376#issuecomment-1226959256) to allow it to deploy to  `github-pages` environment. Also, the branch will need to be added to [action](https://github.com/CraftsmenLtd/BloodConnect/compare/issue-9-doc-as-readable-site?expand=1#diff-87e860af4b9db6c503ed680b6edb6333c6f8d7659f7d1a779a2487466bbc5 …
=> Github action to deploy `docs` folder to Github Pages

docs/README.md
Resolves #9
The github pages doc site landing page did not contain any link to other related docs available in the docs site. Other doc page links added to the landing page of github pages doc site of this repo.
Copy the links provided in the changelog of this PR and paste in the browser. It should lead to respective doc page.
=> I-#9 Other doc links added to BloodConnect github pages home

.github/workflows/deploy-docs.yml
Resolves #9 
Github pages deployment is triggered only when `md` files are modified in the `docs` folder.
- Create commits and push to this branch to test this PR.
- Adding `md` or any other file anywhere except in the `docs` folder should not trigger github workflow to deploy docs.
- Adding/Modifying `md` files anywhere (any hierarchy) inside the `docs` should trigger github workflow to deploy docs. However, it should not trigger for non `md` files.
Please make sure to revert the commits by resetting HEAD and force-push to this branch to remove any unnecessary commits and files from his PR.
https://craftsmenltd.github.io/BloodConnect/
Once this PR is approved, we will need to remove the additional [branch name](https://github.com/CraftsmenLtd/BloodConnect/pull/31/files#diff-87e860af4b9db6 …
=> I#9 deploy docs only for changes in docs

.github/pull_request_template.md, .gitignore, docs/README.md
Fixes #14 
The documentation guideline with tools and formats are being used
Resolves #
N/A
Documentation guideline with mentioning tools, format and learning materials for
- General format of documentation
- API Documentation
- Design tools and docs
- User Story
- Graph and Flow diagrams
- End user documentation
- Readme, Code documentation and Pseudo code
N/A
N/A
Please check english grammer syntax and standard language
N/A
N/A
N/A
N/A
=> I#14: Documentation Gudeline

.github/workflows/deploy-docs.yml, docs/conf.py
Fixes #
Graphviz dot files not rendering
Resolves #
Installs graphviz in the host machine so that the docker container in action has access to dot binary
- Added one extra step to the github action
- Renamed step names cause OCD
If there are any known issues …
=> I-#48 graphviz render

README.md
Fixes #52
Added product details and descriptions to `README.md`.
=> I-#52 README improvement

iac/terraform/aws/api_gw.tf, iac/terraform/aws/auth/outputs.tf, iac/terraform/aws/lambda/outputs.tf, iac/terraform/aws/local.tf, iac/terraform/aws/openapi.tf
Fixes #105 
Added lambda invoke permission to ApiGateway …
=> I-#105: Added lambda invoke permission to ApiGateway

Makefile, openapi/Dockerfile, openapi/docker-compose.yml, openapi/paths/auth/register-organization.json, openapi/paths/cors-options.json, openapi/swagger-ui/index.html, openapi/swagger-ui/nginx.conf, openapi/swagger-ui/process-openapi.sh, openapi/versions/v1.json
Feat: #105 
- Added swagger ui to load openapi files and update the apigateway id
- Added BearerAuth in openapi to set authorization
Please …
=> I 105 add swagger UI to test locally

.github/workflows/ci.yml, Makefile, docs/development/GettingStarted.rst, package.json
Fixes #114
Added ts type check command in package.json scripts, and CI
- Executing command `npm run type-check` should not result in error.
- CI pipeline should include a step for type checking
=> I#114: Adding script for type checking in CI pipeline

.all-contributorsrc, README.md
Fixes #124
Implemented the [all-contributors bot](https://allcontributors.org/) to automatically recognize and display code and non-code contributions in the `README.md` file.
- N/A
1. Verify that the `.all-contributorsrc` file is correctly added to the repository root.
2. Check that the `README.md` file is updated with the new contributors section.
3. Test the bot by commenting on an issue or PR with `@all-contributors please add @gitHubUsername for contribution_type`. Check out the [emoji key](https://allcontributors.org/docs/en/emoji-key) for contribution_types.
- N/A
- N/A
- N/A
None at this time. The bot should function as expected once merged.
The bot allows contributors to self-add their contributions by commenting on issues or pull requests, automating the recognition process for …
=> I-#124 Implemented All-Contributors Bot for Automated All Contributors Recognition

.github/workflows/ci.yml, Makefile
Feat: #118 
Add LocalStack Pro access in the GitHub CI workflow.
Please assess risk & follow up on deployment of this PR. Elaborate your choice …
=> I-#118: Added Localstack pro auth token

docs/devops/LambdaOpenapiIntegration.rst, docs/devops/index.rst
Feat: #96 
Added a doc for `Module With Multiple Lambda Functions and Integrating With OpenAPI`
Please assess risk & follow up on deployment of …
=> I-96 Added documentation for Lambda Functions and OpenAPI Integration

.github/workflows/deploy-stage.yml
Fixes #118 
Initialize Stage deployment workflow …
=> I-#118: Initialize Stage deployment workflow

.gitignore
Temporary change to ignore `local.bru` file which changes on every run on local machine
=> temporary ignore local.bru

docs/devops/LambdaOpenapiIntegration.rst, docs/devops/Pipelines.rst
Fixes #118 
- Fixed pipeline documentation format issue …
=> 118: Fixed pipeline documentation format issue

README.md
Fixes #
Resolves #
Adds github workflow badges
Add any additional notes or …
=> Update README.md to add workflow badges

iac/terraform/aws/api_gw.tf, iac/terraform/aws/cognito/cognito.tf, iac/terraform/aws/cognito/output.tf, iac/terraform/aws/openapi.tf, openapi/paths/auth/register-organization.json, openapi/versions/v1.json
Fixes #
Implemented authorisation process in API gateway endpoint
Resolves #
Implemented authorisation to access `API` endpoints. Without appropriate key user won't be access specific endpoints. 
Add any additional notes …
=> Cognito authorisation with API gateway

deployment/aws/terraform/provider.tf, deployment/localstack/terraform/provider.tf
Fixes #
There was new issue with terraform deployment after the latest release of hashicorp/aws(5.72). this pr is for freezing the hashicorp/aws version to **5.70**
error example: https://github.com/CraftsmenLtd/BloodConnect/actions/runs/11367680530/job/31620976681
If there are any known issues or limitations with the changes made …
=> Freeze hashicorp/aws version

openapi/Dockerfile, openapi/docker-compose.yml, openapi/swagger-ui/generate-token.sh, openapi/swagger-ui/index.html, openapi/swagger-ui/nginx.conf
Feat: #178 
Added authentication for Swagger UI
When Docker Compose starts for swagger ui, it creates a Cognito user, retrieves an authentication token, and updates the Swagger UI HTML with the token for authenticated access. …
=> I-#178: Added authentication for Swagger ui

iac/terraform/aws/cognito/cognito.tf
Fixes #
Update cognito schemas for missing attributes …
=> Update cognito schemas for missing attributes

docs/devops/LambdaOpenapiIntegration.rst, iac/terraform/aws/auth/lambdas.tf, iac/terraform/aws/auth/variables.tf, iac/terraform/aws/cognito/lambdas.tf, iac/terraform/aws/cognito/variables.tf, iac/terraform/aws/donation/lambdas.tf, iac/terraform/aws/donation/variables.tf, iac/terraform/aws/lambda/lambda.tf, iac/terraform/aws/lambda/local.tf, iac/terraform/aws/local.tf, iac/terraform/aws/modules.tf, openapi/Dockerfile, openapi/paths/cors-options.json, openapi/versions/v1.json
Fixes NO-TICKET
- Moved lambda archive path to lambda module
- also fixed some known openapi and swagger issues
Please assess risk & follow up …
=> Moved lambda archive path to lambda module

core/application/technicalImpl/cognito/CognitoModel.ts, core/application/tests/mocks/mockCognitoUserData.ts, core/services/aws/commons/cognito/CognitoOperations.ts, core/services/aws/package-lock.json, core/services/aws/package.json, core/services/aws/tests/commons/cognito/CognitoOperations.test.ts, core/services/aws/tests/user/cognitoTrigger/lambdas/postConfirmationTrigger.test.ts, core/services/aws/user/cognitoTrigger/lambdas/postConfirmationTrigger.ts, iac/terraform/aws/cognito/cognito.tf, iac/terraform/aws/cognito/data.tf, iac/terraform/aws/cognito/lambdas.tf, iac/terraform/aws/cognito/policy.tf
Feat: #191 
Add userId to Cognito in Post-Confirmation after adding user to dynamodb
Please assess risk & follow up on deployment of this PR. …
=> I-#191: Add userId to Cognito in Post-Confirmation

Makefile, openapi/docker-compose.yml, openapi/swagger-ui/generate-token.sh, openapi/swagger-ui/process-openapi.sh, openapi/swagger-ui/setup-swagger.sh, openapi/versions/v1.json
Right now because of some bugs we can't use `localstack` for testing. and we are testing by deploying in aws. but it takes time to create a user manually and get the id token and then test apis in a branch deployment.
so updated the swagger to test api gateway from a branch deployment. it takes the deployed branch name, email and password.
new command for running swagger ui
```
make swagger-ui branch=<branch_name> email=<email> password=<password>
```
updated script creates a user in the user pool and gets the IdToken and also gets the apigateway id for swagger ui
If you have any specific requests or suggestions …
=> Update swagger ui to create user and test api in aws

.github/workflows/destroy-branch.yml
Branch Destruction is giving Terraform not found error. Fixed it by running the terraform command inside the docker container.
Please assess …
=> Fix destroy branch for terraform not found issue

commons/dto/DonationDTO.ts, core/application/bloodDonationWorkflow/BloodDonationService.ts, core/application/bloodDonationWorkflow/Types.ts, core/application/technicalImpl/dbModels/DonorSearchModel.ts, core/application/technicalImpl/stepFunctions/StepFunctionModel.ts, core/application/tests/bloodDonationWorkflow/BloodDonationService.test.ts, core/application/tests/mocks/mockStepfunctionInput.ts, core/services/aws/bloodDonation/calculateDonorsToNotify.ts, core/services/aws/bloodDonation/donorRequestRouter.ts, core/services/aws/bloodDonation/donorSearchEvaluator.ts, core/services/aws/commons/stepFunction/StepFunctionOperations.ts, core/services/aws/tests/bloodDonation/calculateDonorsToNotify.test.ts, core/services/aws/tests/bloodDonation/donorRequestRouter.test.ts, iac/terraform/aws/donor_search/donor_search.json, iac/terraform/aws/donor_search/lambdas.tf, iac/terraform/aws/donor_search/stepFunction.tf, iac/terraform/aws/eventbridge/eventbridge.tf
Fixes #156 
- Added donor search process for stepfunction
- updated sone existing functions and unittests
Resolves #
Add any additional notes or …
=> 156 donor search Step function step

.github/workflows/aws-terraform.yml
Fixes : no ticket
Moved FIREBASE_TOKEN_S3_URL from var to secret
Please assess risk & follow up on deployment of this PR. Elaborate your choice …
=> Moved FIREBASE_TOKEN_S3_URL from var to secret

core/application/notificationWorkflow/NotificationService.ts, core/application/technicalImpl/sns/SNSModel.ts, core/services/aws/commons/sns/SNSOperations.ts, iac/terraform/aws/notification/policies.tf
Fixes #
Fixed same device token issue when different user from same device login
Please assess risk & follow up on deployment of this PR. …
=> Fixed multiple user issue for same device

openapi/integration/aws/donors/get-donor.json, openapi/paths/donors/donors.json, openapi/versions/v1.json
Fixes #246 
Added get donor api so that we can  …
=> I-#246: Added get donor api

.github/workflows/ci.yml, .github/workflows/deploy-stage.yml, core/application/tests/userWorkflows/UserService.test.ts, core/application/userWorkflow/UserService.ts, deployment/localstack/terraform/resources.tf, iac/terraform/aws/user/lambdas.tf, iac/terraform/aws/user/variables.tf
Fixes #
Strange name for wait period between donations
Resolves # …
=> NO-TICKET: fix weird name for donation cool down

core/application/models/dbModels/BloodDonationModel.ts, core/application/tests/mocks/mockDonationRequestData.ts, core/application/tests/technicalImpl/dbModels/BloodDonationModel.test.ts, openapi/integration/aws/donations/get-posts.json, openapi/paths/donations/posts.json, openapi/versions/v1.json
Fixes #259 
Added get public donation posts api …
=> I-#259: Added get public donation posts api

openapi/integration/aws/donations/get-responses.json, openapi/paths/donations/responses.json, openapi/versions/v1.json
Fixes #259 
Added get user responses api …
=> I-#259: Added get user responses api

commons/dto/NotificationDTO.ts, core/application/bloodDonationWorkflow/BloodDonationService.ts, core/application/bloodDonationWorkflow/Types.ts, core/application/models/dbModels/DonationNotificationModel.ts, core/application/models/dbModels/NotificationModel.ts, core/application/models/policies/repositories/BloodDonationRepository.ts, core/application/models/policies/repositories/NotificationRepository.ts, core/application/notificationWorkflow/NotificationService.ts, core/application/notificationWorkflow/Types.ts, core/application/tests/bloodDonationWorkflow/BloodDonationService.test.ts, core/services/aws/bloodDonation/acceptDonationRequest.ts, core/services/aws/bloodDonation/updateBloodDonation.ts, core/services/aws/commons/ddb/BloodDonationDynamoDbOperations.ts, core/services/aws/commons/ddb/NotificationDynamoDbOperations.ts, core/services/aws/notification/registerUserDevice.ts, core/services/aws/notification/sendPushNotification.ts, core/services/aws/tests/bloodDonation/updateBloodDonation.test.ts, core/services/aws/tests/cannedData/updateBloodDonationLambdaEvent.ts, iac/terraform/aws/donation/policies.tf
Fixes #
- when updating blood donation, we also need to update the notification payloads we sent to users. here I updated notification payload for the blood donation update request.
- also added some improvements for notification service
If there are any known issues or limitations with the changes made in this pull request, …
=> update notification payload when updating blood donation

core/application/bloodDonationWorkflow/BloodDonationService.ts, core/application/models/dbModels/AcceptDonationModel.ts, core/application/models/dbModels/BloodDonationModel.ts, core/application/models/dbModels/DonationNotificationModel.ts, core/application/tests/technicalImpl/dbModels/BloodDonationModel.test.ts, core/services/aws/bloodDonation/completeDonationRequest.ts
Bug Issue #296 
- When attempting to update an item in DynamoDB, if the fields needed in GSI1PK, GSI1SK, or LSI1SK are not provided, they are being set to undefined in the update request. to fix that updated dynamodb models with optional indexes
If there are any known issues or limitations with the changes made in this pull request, …
=> 296 Handle undefined value during DynamoDB update

Makefile, docs/devops/AWSDeploymentLocally.rst, docs/devops/index.rst
Fixes #
Added commands and doc to deploy branch locally …
=> NO-TICKET: Added commands to deploy branch locally

clients/mobile/app.config.ts, clients/mobile/src/components/donation/PostCard.tsx, clients/mobile/src/components/donation/Posts.tsx, clients/mobile/src/components/toast/index.tsx, clients/mobile/src/components/toast/useToast.ts, clients/mobile/src/donationWorkflow/donationService.ts, clients/mobile/src/myActivity/MyActivityTab.tsx, clients/mobile/src/myActivity/myPosts/details/Detail.tsx, clients/mobile/src/myActivity/useMyActivity.ts
Fixes #253 
Resolves #
User can cancel his/her donation request
When a user requested for blood, he/she should be able to cancel the request.
With this PR we implemented this feature
If there are any known issues or limitations with the changes made in this …
=> I-#253 User can cancel his/her donation request

clients/mobile/src/donationWorkflow/createUpdateDonation/Donation.tsx
Fixes #285 
Resolves #
scroll issue on create post page issue fix
We're wrapping the full scroll view with a container which causes a side effect on scrolling.
In this PR I removed the container to fix the issue
If there are any known issues or limitations …
=> I-#285 create post page scrolling issue fix

core/services/aws/bloodDonation/cancelBloodDonation.ts
Fixes #253 
Resolves #
Success boolean field added to cancel post API response
We need this boolean flag for the frontend which was previously missing in the response
If there are any known issues or limitations with the changes made in this pull request, …
=> I-#253 success boolean field added to cancel post api response

core/services/aws/user/createUser.ts, iac/terraform/aws/user/lambdas.tf, openapi/components/schemas/users/create-user-payload.json, openapi/integration/aws/users/post-user.json, openapi/paths/users/users.json
Fixes #266 
Resolves #
Separated user profile create and update API.
We have decided to separate the Create User Profile and Update User Profile functionalities into distinct APIs.
In this PR, there are no changes to the Service layer code. The updates are limited to the Handler layer, where the logic has been split to accommodate this separation.
This change is being made to facilitate future enhancements, such as implementing a feature where administrators need to approve user profile update requests.
If you have any specific requests or …
=> I-#266 BE: Separated user profile create and update API.

core/application/models/dbModels/BloodDonationModel.ts, core/application/tests/mocks/mockDonationRequestData.ts, core/application/tests/technicalImpl/dbModels/BloodDonationModel.test.ts, core/services/aws/bloodDonation/acceptDonationRequest.ts, core/services/aws/bloodDonation/cancelBloodDonation.ts, core/services/aws/bloodDonation/completeDonationRequest.ts, core/services/aws/bloodDonation/createBloodDonation.ts, core/services/aws/bloodDonation/updateBloodDonation.ts, core/services/aws/donorSearch/donorRequestRouter.ts, core/services/aws/tests/bloodDonation/createBloodDonation.test.ts, core/services/aws/tests/bloodDonation/updateBloodDonation.test.ts, core/services/aws/user/createUser.ts, openapi/integration/aws/donations/vtl/requestTemplates/get-posts.vtl, openapi/integration/aws/donations/vtl/requestTemplates/patch-cancel-donation.vtl, openapi/integration/aws/donations/vtl/requestTemplates/patch-donation.vtl, openapi/integration/aws/donations/vtl/requestTemplates/patch-update-response.vtl, openapi/integration/aws/donations/vtl/requestTemplates/post-complete-donation.vtl, openapi/integration/aws/donations/vtl/requestTemplates/post-donation.vtl, openapi/integration/aws/donations/vtl/responseTemplates/get-donations.vtl
Fixes #
- Updated get posts query not to include my posts and added createdAt value in GSI1SK to sort it
- Refactored the accept donation lambda and checked if the user blood group matches the requested blood group
- Added HTTP logger for API gateway lambdas
If there are any known issues or limitations with the changes made in this …
=> Fixed minor issues 

core/services/aws/bloodDonation/getDonationRequest.ts, iac/terraform/aws/donation/lambdas.tf, openapi/integration/aws/donations/get-donation.json, openapi/integration/aws/donations/vtl/requestTemplates/get-donation.vtl, openapi/integration/aws/donations/vtl/responseTemplates/get-donation.vtl, openapi/paths/donations/donation.json, openapi/versions/v1.json
Fixes #
- Added get donation api
Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other …
=> NO-TICKET: Added get donation api

clients/mobile/src/donationWorkflow/donationPosts/donorResponse/UI/ResponseDonationRequest.tsx
Fixes #No-Ticket
Resolves #
We'll hide the phone until the user accepted the blood request post
Previously we're showing seekers phone number regard less of the donor accepted the request or not.
In this PR, we're masking the phone number from mobile app only until the post has been accepted by the donor.
If applicable, provide a link to a live demo …
=> I-#NO-TICKET hide phone number until the request has been accepted.

clients/mobile/app.config.ts, clients/mobile/src/components/StateAwareRenderer.tsx, clients/mobile/src/components/donation/DonorCard.tsx, clients/mobile/src/components/donation/PostCard.tsx, clients/mobile/src/donationWorkflow/createUpdateDonation/useBloodRequest.ts, clients/mobile/src/donationWorkflow/donationHelpers.ts, clients/mobile/src/donationWorkflow/donationPosts/donorResponse/hooks/useResponseDonationRequest.ts, clients/mobile/src/donationWorkflow/donationService.ts, clients/mobile/src/donationWorkflow/donorResponse/useDonationResponse.ts, clients/mobile/src/myActivity/MyActivityTab.tsx, clients/mobile/src/myActivity/context/MyActivityProvider.tsx, clients/mobile/src/myActivity/donorProfile/DonorProfile.tsx, clients/mobile/src/myActivity/donorProfile/useDonorProfile.ts, clients/mobile/src/myActivity/donorTracking/bloodRequestStatus/RequestStatusScreen.tsx, clients/mobile/src/myActivity/donorTracking/bloodRequestStatus/useRequestStatus.ts, clients/mobile/src/myActivity/donorTracking/donorConfirmation/DonorConfirmationScreen.tsx, clients/mobile/src/myActivity/donorTracking/donorConfirmation/useDonorConfirmation.ts, clients/mobile/src/myActivity/myPosts/details/Detail.tsx, clients/mobile/src/myActivity/myPosts/donorResponses/DonorResponses.tsx, clients/mobile/src/myActivity/useMyActivity.ts, clients/mobile/src/setup/clients/response.ts, clients/mobile/src/setup/clients/useFetchData.ts, clients/mobile/src/setup/constant/consts.ts, clients/mobile/src/setup/constant/screens.ts, clients/mobile/src/setup/navigation/navigationTypes.ts, clients/mobile/src/setup/navigation/routes.ts, clients/mobile/src/setup/notification/NotificationProvider.tsx, clients/mobile/src/setup/notification/scheduleNotification.ts, clients/mobile/src/userWorkflow/services/userServices.ts, clients/mobile/src/utility/formatting.ts
Fixes #270 
Implement a local notification system in the app to keep both donors and seekers informed about donation-related updates. The following features were added:
- **Seeker Notifications**: When a seeker creates a post, they will receive a notification 1 day after the scheduled donation date and time to confirm the donors.
- **Donor Reminders**: Donors will receive reminders 3 hours and 1 hour before the scheduled donation time to ensure they are reminded about their commitment.
- **Clickable Donation Points**: The donation points listed in the app are now clickable. When clicked, they will open Google Maps with the location of the donation point, making it easier for users to navigate to the location.
Resolves #
Used when the changes in the pull request indirectly resolve another …
=> Implement Local Notifications for Donation Reminders and Confirmation

core/application/models/dbModels/DonationRecordModel.ts, core/application/models/policies/repositories/LocationRepository.ts, core/application/tests/userWorkflows/UserService.test.ts, core/application/userWorkflow/UserService.ts, core/services/aws/bloodDonation/completeDonationRequest.ts, core/services/aws/commons/ddb/LocationDynamoDbOperations.ts, iac/terraform/aws/donation/policies.tf
Fixes #
- Update user availability when donation is complete …
=> NO-TICKET: Update user availability when donation is complete

clients/mobile/app.json, clients/mobile/package-lock.json, clients/mobile/package.json, clients/mobile/src/donationWorkflow/createUpdateDonation/useBloodRequest.ts, clients/mobile/src/myActivity/MyActivityTab.tsx
Fixes #NO-TICKET
Resolves #
1. After create or update donation post, will redirect to my post page
2. Update donation payload fixed
3. Added refresh feature for my posts screen
4. remove EAS owner from `app.json`
If there are any known issues or limitations …
=> I-#NO-TICKET Donation post update bug fix and redirect screen changed

clients/mobile/src/myActivity/context/MyActivityProvider.tsx, clients/mobile/src/userWorkflow/account/UI/Account.tsx, clients/mobile/src/utility/deviceRegistration.ts
Fixes #NO-TICKET
Resolves #
1. Device registration issue
2.  First time my posts loading bug
Add any additional notes or comments you think are …
=> I-#NO-TICKET my posts initial data loading bug fix

core/services/aws/commons/httpLogger/LambdaLogger.ts, core/services/aws/logger/addUiLogs.ts, iac/terraform/aws/api_gw.tf, iac/terraform/aws/donation/lambdas.tf, iac/terraform/aws/lambda/lambda.tf, iac/terraform/aws/lambda/variables.tf, iac/terraform/aws/local.tf, iac/terraform/aws/logger/data.tf, iac/terraform/aws/logger/lambdas.tf, iac/terraform/aws/logger/modules.tf, iac/terraform/aws/logger/outputs.tf, iac/terraform/aws/logger/policies.tf, iac/terraform/aws/logger/variables.tf, iac/terraform/aws/modules.tf, openapi/components/schemas/donations/create-request-payload.json, openapi/components/schemas/logger/create-logs-payload.json, openapi/components/schemas/users/create-user-payload.json, openapi/integration/aws/logger/post-logger.json, openapi/integration/aws/logger/vtl/requestTemplates/post-logger.vtl, openapi/integration/aws/logger/vtl/responseTemplates/post-logger.vtl, openapi/paths/logger/logger.json, openapi/versions/v1.json
Feat #326 
- added logger API to save frontend error logs
- Added log group for API gateway
Please assess risk & follow up on deployment of …
=> 326 added logger api to save frontend error logs for temporary use

iac/terraform/aws/lambda/lambda.tf
=> NO-TICKET: Update lambda log group name

clients/mobile/src/donationWorkflow/donationPosts/donorResponse/hooks/useResponseDonationRequest.ts, clients/mobile/src/myActivity/context/MyActivityProvider.tsx
Fixes #
- if i accepted a request, when i goto the details page again. it should show request already accepted
Resolves #
If there are any known issues or limitations with the changes made …
=> Fix: Show "Request Already Accepted" on Details Page for Accepted Requests

clients/mobile/src/components/inputElement/DateTimePicker.tsx, clients/mobile/src/donationWorkflow/donationPosts/donorResponse/UI/ResponseDonationRequest.tsx, clients/mobile/src/donationWorkflow/donationPosts/donorResponse/UI/createStyles.tsx, clients/mobile/src/setup/theme/darkTheme.ts, clients/mobile/src/setup/theme/index.ts, clients/mobile/src/setup/theme/lightTheme.ts, clients/mobile/src/userWorkflow/personalInfo/UI/AddPersonalInfo.tsx
Fixes #235 
Resolves #
- Horizontal line separation breaking issue
- Style modification
=> I 235 update accept donation app

commons/dto/DonationDTO.ts, core/application/bloodDonationWorkflow/BloodDonationService.ts, core/application/bloodDonationWorkflow/DonorSearchService.ts, core/application/bloodDonationWorkflow/Types.ts, core/application/models/dbModels/BloodDonationModel.ts, core/application/models/dbModels/DonorSearchModel.ts, core/application/tests/bloodDonationWorkflow/BloodDonationService.test.ts, core/application/tests/bloodDonationWorkflow/DonorSearchService.test.ts, core/application/tests/mocks/mockDonationRequestData.ts, core/application/tests/technicalImpl/dbModels/BloodDonationModel.test.ts, core/services/aws/bloodDonation/createBloodDonation.ts, core/services/aws/commons/lambda/ApiGateway.ts, core/services/aws/tests/bloodDonation/createBloodDonation.test.ts, openapi/integration/aws/donations/vtl/requestTemplates/get-posts.vtl, openapi/integration/aws/donations/vtl/responseTemplates/get-posts.vtl
- Updated public post api to filter old posts
- added `seekerName` under donation entry
- change `id` of the donation request to `requestPostId`
- updated donation `GSI1SK` format and added `createdAt` field at the beginning for sorting it by date
If there are any known issues or limitations with the changes made in this pull …
=> I-#326: Updated public post api to filter old posts

.github/workflows/deploy-prod.yml, iac/terraform/aws/cloudfront/cloudfront.tf, iac/terraform/aws/cognito/cognito.tf
Fixes #NO-TICKET
Fixed prod pipeline issues …
=> NO-TICKET: Updated prod pipeline

clients/mobile/src/userWorkflow/account/UI/Account.tsx, clients/mobile/src/userWorkflow/account/UI/createStyle.tsx
Fixes #
Temporarily commented featureless buttons on `Account` page
=> I-#326 temporary remove featureless button on account page

clients/mobile/src/userWorkflow/personalInfo/hooks/useAddPersonalInfo.ts, core/services/aws/bloodDonation/completeDonationRequest.ts, openapi/integration/aws/users/vtl/responseTemplates/get-user.vtl
=> NO-TICKET: Updated last donation date when completing donation

core/application/notificationWorkflow/NotificationService.ts, core/services/aws/bloodDonation/acceptDonationRequest.ts, openapi/integration/aws/donations/vtl/responseTemplates/get-donations.vtl
Fixed notification creation status issue …
=> NO-TICKET: Fixed notification creation status issue

core/application/bloodDonationWorkflow/DonorSearchService.ts, iac/terraform/aws/donor_search/local.tf
Fixes #
- Fixed donor search issue when updating donation
- Rerunning donor search if blood count increased or donation date time changed
- increased max geohash neighbor level to 70
Add any additional notes or comments you …
=> NO-TICKET: Fixed donor search issue when updating donation

core/services/aws/donorSearch/queryEligibleDonors.ts
Added all city query if enough donors not found in max neighbor level. later we will remove it, but for now it will be usefull
Please assess …
=> NO-TICKET: Added all city query if enough donors not found in max neighbor level

clients/mobile/src/donationWorkflow/donationPosts/donorResponse/UI/ResponseDonationRequest.tsx
Fixes #No-Ticket
Resolves #
We're hiding the phone number until the donor accept the request, now we changed the logic based on the post status rather than handling from the frontend only.
If there are any known issues or limitations with the changes made in …
=> I-#NO-TICKET logic changed for how we're handling the phone number hidden works

Makefile, iac/terraform/aws/cloudfront/cloudfront.tf, iac/terraform/aws/cloudfront/cloudfront_template.json, iac/terraform/aws/cloudfront/outputs.tf, iac/terraform/aws/cloudfront/policy.tf, iac/terraform/aws/cognito/cognito.tf, iac/terraform/aws/route53.tf, iac/terraform/aws/variables.tf
For some reason terraform is failing to create CloudFront. I need more time to fix the terraform issue. for now, changing the CloudFront config from Terraform to CloudFormation. so that our branch deployment workflow continues without interruptions.
If there are any known issues or limitations with the changes made in this pull …
=> I-#386: Changed the CloudFront config from terraform to CloudFormation

clients/mobile/src/components/inputElement/TextArea.tsx, clients/mobile/src/donationWorkflow/createUpdateDonation/Donation.tsx, clients/mobile/src/donationWorkflow/createUpdateDonation/useBloodRequest.ts, clients/mobile/src/utility/validator.ts
Fixes #364 
- Fix New Line Error in Short Description Field on Post Create Page
Resolves #
Add any additional notes or comments you think are …
=> Fix new line issue in short description field.

clients/mobile/src/components/donation/PostCard.tsx, clients/mobile/src/components/donation/Posts.tsx, clients/mobile/src/donationWorkflow/donationPosts/DonationHeader.tsx, clients/mobile/src/myActivity/donorTracking/bloodRequestStatus/RequestStatusScreen.tsx, clients/mobile/src/myActivity/donorTracking/bloodRequestStatus/useRequestStatus.ts, clients/mobile/src/myActivity/donorTracking/donorConfirmation/DonorConfirmationScreen.tsx, clients/mobile/src/myActivity/donorTracking/donorConfirmation/useDonorConfirmation.ts, clients/mobile/src/myActivity/donorTracking/useCompleteDonation.ts, clients/mobile/src/myActivity/myPosts/details/Detail.tsx
Fixes #374 #376 #381 #384 
When the network is not available, it is considered an error, which prevents the main content from rendering. To address this, I have implemented an error component and render it with a refresh controller.
If a request is canceled or completed, I have disabled the update and cancel buttons.
If no donor is found for a post, when the user clicks the "Yes, Manage" button, it first checks if any donor is available. If a donor is present, it moves to the select page. If no donor is present, clicking the "Yes, Manage" button will call the API to complete the post.
Resolves #
Link to the relevant issue(s) or provide a …
=> Fix Issues with Swipe Refresh, Request Status Updates, Post Completion, and Donor List Visibility

core/application/tests/userWorkflows/userMessages.test.ts, core/application/userWorkflow/userMessages.ts, core/application/utils/messageConstants.ts
Fixes #342 
New design applied to email templates which was sent to users with text fallback support and following consistent branding and color scheme aligned with the app's design.
New design looks like below
Add any …
=> I-#342-email templates are redesigned to follow brand guidelines and text fallback support added too.

clients/mobile/src/components/inputElement/Dropdown.tsx, clients/mobile/src/donationWorkflow/createUpdateDonation/Donation.tsx
Fixes #360 
Resolves #
City dropdown needed a search functionality so that end user easily search the city, in this PR it's implemented 
Add any …
=> I-#360-searching enabled in city dropdown

clients/mobile/src/components/inputElement/Checkbox.tsx, clients/mobile/src/userWorkflow/personalInfo/UI/AddPersonalInfo.tsx
Fixes #398
`Terms and Conditions` section was overflowing outside the Personal Info screen. The layout has been adjusted to ensure proper alignment and containment within the screen boundaries.
Resolves #
If there are any known issues or limitations with the …
=> Fix: Terms and Conditions section layout issue on Personal Info screen

docs/development/GettingStarted.rst
=> NO-TICKET: Add swagger command instruction

clients/mobile/src/myActivity/MyActivityTab.tsx, clients/mobile/src/myActivity/myPosts/details/Detail.tsx, clients/mobile/src/myActivity/useMyActivity.ts, clients/mobile/src/setup/navigation/navigationTypes.ts, core/services/aws/bloodDonation/acceptDonationRequest.ts, openapi/integration/aws/donations/vtl/responseTemplates/get-responses.vtl
Fixes #372 
Added "View Details" button to each card in the My Responses page. The button allows donors to navigate to the details page.
Resolves # …
=> Add View Details button in My Responses page to redirect to details page with seeker's contact information

core/services/aws/bloodDonation/acceptDonationRequest.ts, docs/architecture/SystemDesign.rst, openapi/integration/aws/donations/vtl/requestTemplates/get-responses.vtl
=> NO-TICKET: update public post query

clients/mobile/src/donationWorkflow/donationPosts/donorResponse/UI/ResponseDonationRequest.tsx
Fixes #
Replace patient name to seeker name.
Resolves #
Please …
=> Replace patient name to seeker name.

openapi/integration/aws/donations/get-posts.json, openapi/integration/aws/donations/vtl/requestTemplates/get-posts.vtl
Updated public post cache time and fix bug …
=> NO-TICKET: Updated public post cache time and fix bug

Makefile, makefiles/terraform.mk
Updated local branch deployment and separate terraform make commands
Please assess risk & follow up on deployment of this PR. Elaborate your …
=> NO-TICKET: Updated local branch deployment and separate terraform make commands

iac/terraform/aws/cloudfront/cloudfront_template.json
Updated cloudfront cache for /api origin with 0 ttl …
=> NO-TICKET: Updated cloudfront cache for /api origin with 0 ttl

.github/workflows/ci-checks.yml
=> NO-TICKET: update ci pipeline

docs/legal/DataDeletionInstruction.rst, docs/legal/index.rst
Added user data deletion instructions for facebook …
=> NO-TICKET: Added user data deletion instructions for facebook

iac/terraform/aws/cognito/cognito.tf, iac/terraform/aws/cognito/local.tf
Updated cognito config for prod
Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than …
=> NO-TICKET: Updated cognito config for prod

openapi/components/schemas/donations/create-request-payload.json
=> NO-TICKET: Update donation payload

core/services/aws/user/updateUser.ts
=> NO-TICKET: Fixed update user api

core/services/aws/notification/sendPushNotification.ts
Fixed duplicate notification issue
Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other …
=> NO-TICKET: Fixed duplicate notification issue

clients/mobile/src/components/donation/PostCard.tsx, clients/mobile/src/donationWorkflow/createUpdateDonation/useBloodRequest.ts, clients/mobile/src/donationWorkflow/donationHelpers.ts, clients/mobile/src/donationWorkflow/donationPosts/donorResponse/UI/ResponseDonationRequest.tsx, clients/mobile/src/myActivity/myPosts/details/Detail.tsx, clients/mobile/src/userWorkflow/editUserProfile/UI/EditProfile.tsx, clients/mobile/src/userWorkflow/userProfile/UI/Profile.tsx
=> I-#NO-TICKET-small UI fixes for mobile app

core/services/aws/bloodDonation/acceptDonationRequest.ts, core/services/aws/notification/sendPushNotification.ts
Fixed bloodQuantity field in notification …
=> NO-TICKET: Fixed bloodQuantity field in notification

iac/terraform/aws/eventbridge/eventbridge.tf, iac/terraform/aws/eventbridge/variables.tf, iac/terraform/aws/modules.tf
Fixes #
- We were having a race condition with event-bridge pipes for streams on ddb. This pr resolves that by adding a wait.
Resolves #
Add any …
=> NO-TICKET: Fixed eventbridge pipe creation issue

README.md, iac/terraform/aws/cognito/cognito.tf, iac/terraform/aws/cognito/local.tf, iac/terraform/aws/cognito/output.tf, iac/terraform/aws/maps/lambdas.tf, iac/terraform/aws/maps/variables.tf, iac/terraform/aws/modules.tf, iac/terraform/aws/route53.tf
- Added custom URL for cognito oauth signing
- Removed JetBrains from Open source support
Please assess risk & follow up on deployment of this …
=> NO-TICKET: Added custom url for cognito oauth signin

iac/terraform/aws/eventbridge/eventbridge.tf
Fixed eventbridge pipe issue
Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than …
=> NO-TICKET: Fixed eventbridge pipe issue

iac/terraform/aws/cognito/cognito.tf
Fixed cognito callback url issue
Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other …
=> NO-TICKET: Fixed cognito callback url issue

clients/mobile/App.tsx, clients/mobile/app.json, clients/mobile/firebase.json, clients/mobile/package-lock.json, clients/mobile/package.json, clients/mobile/src/setup/monitoring/CrashlyticsService.ts, clients/mobile/src/setup/monitoring/IMonitoringService.ts, clients/mobile/src/setup/monitoring/MonitoringService.ts
Fixes #439 
Added Firebase Crashlytics to the React Native app for tracking crashes and logging errors. Implemented global error handling and created a service for easy future integration with other monitoring tools.
Resolves #
If there are any known issues …
=> Integrate Firebase Crashlytics for Error Monitoring and Reporting

core/application/maps/MapsService.ts, core/application/maps/dto/Maps.ts, core/application/models/maps/MapsProvider.ts, core/application/package.json, core/services/aws/maps/getGeoCode.ts, core/services/aws/maps/getPlaceAutoComplete.ts, core/services/maps/MapsHandler.ts, core/services/maps/jest.config.ts, core/services/maps/package-lock.json, core/services/maps/package.json, core/services/maps/providers/GoogleMaps.ts, core/services/maps/tests/mapsHandler.test.ts, jest.config.ts
Fixes #No Ticket
As discussed we're refactoring the maps module structure to the current code base to follow a common practice.
Add any additional notes or …
=> Maps module structure refactored to follow current code base structure

.github/workflows/deploy-docs.yml
Fixed doc pipeline error
This is the error: https://github.com/CraftsmenLtd/BloodConnect/actions/runs/13781291770/job/38539846158
Please assess …
=> NO-TICKET: Fixed doc pipeline error

.github/workflows/deploy-mobile-preview.yml
=> NO-TICKET: added mobile preview deployment

clients/mobile/src/userWorkflow/editUserProfile/UI/EditProfile.tsx
Fixed location service missing base api issue …
=> NO-TICKET: fixed location service missing base api issue

.github/workflows/build-mobile.yml, .github/workflows/eas-mobile.yml
=> I-#221: temp merge to create pipeline

clients/mobile/src/userWorkflow/editUserProfile/hooks/useEditProfile.ts
Fixed edit profile missing base API issue …
=> NO-TICKET: fixed edit profile missing base api issue

clients/mobile/src/donationWorkflow/donationPosts/donorResponse/UI/ResponseDonationRequest.tsx, clients/mobile/src/donationWorkflow/donationPosts/donorResponse/hooks/useResponseDonationRequest.ts, core/services/aws/bloodDonation/completeDonationRequest.ts
NO-TICKET: updated post details to enable accept button only for the same blood group
Please assess risk & follow up on deployment of this PR. …
=> NO-TICKET: updated post details to enable accept button only for same blood group

clients/mobile/src/donationWorkflow/donationPosts/DonationHeader.tsx, clients/mobile/src/donationWorkflow/donationPosts/DonationPosts.tsx, clients/mobile/src/donationWorkflow/donationPosts/useDonationPosts.ts, clients/mobile/src/donationWorkflow/donationService.ts, openapi/integration/aws/donations/get-posts.json, openapi/integration/aws/donations/vtl/responseTemplates/get-posts.vtl, openapi/paths/donations/posts.json
Fixes #No Ticket
Resolves #
Previously we weren't able to filter by blood group in public post, In this PR introduce that as a feature so that user can filter using there blood group.
If there are any known issues or limitations with the changes made in this …
=> added filter button to public post page

.github/workflows/build-mobile.yml, .github/workflows/eas-mobile.yml
Fixes #
- We were printing google secrets token file in our mobile pipeline, we've now enabled an encryption so that i doesn't print it to screen
Resolves #
If there are any known issues or limitations with the changes made in this pull request, describe …
=> fix(NO-TICKET): fix major security leak by encrypting google secrets

clients/mobile/src/donationWorkflow/createUpdateDonation/useBloodRequest.ts, clients/mobile/src/myActivity/myPosts/details/Detail.tsx, core/application/notificationWorkflow/NotificationService.ts, core/services/aws/bloodDonation/completeDonationRequest.ts
Fixes #HotFix
Resolves #
- Complete Request button disabled if status Complete or Expired or Cancelled
- Thank you local notification removed as it's meant for donor not seeker
- Thank you notification will be sent to donor immediately after donation complete.
If applicable, …
=> HotFix: Donor intended notification send to seeker

iac/terraform/aws/cognito/cognito.tf, iac/terraform/aws/cognito/local.tf
Fixes # N/A
Resolves Incorrect redirect url
Please assess risk & …
=> fix(NO-TICKET): fix redirect mismatch

clients/mobile/eas.json
=> NO-TICKET: added EXPO_USE_METRO_WORKSPACE_ROOT=1 in eas.json

clients/mobile/src/api/hooks/useFetchCountry.tsx, clients/mobile/src/authentication/login/UI/Login.tsx, clients/mobile/src/authentication/login/hooks/useLogin.ts, clients/mobile/src/components/inputElement/PhoneNumberInput.tsx, clients/mobile/src/components/inputElement/hooks/usePhoneNumberInput.ts, clients/mobile/src/components/mapView/useMapView.ts, clients/mobile/src/donationWorkflow/createUpdateDonation/useBloodRequest.ts, clients/mobile/src/donationWorkflow/donationPosts/DonationPosts.tsx, clients/mobile/src/myActivity/MyActivityTab.tsx, clients/mobile/src/setup/clients/FetchClient.ts, clients/mobile/src/setup/constant/localStorageKeys.ts, clients/mobile/src/setup/notification/saveDeviceToken.ts, clients/mobile/src/userWorkflow/account/UI/Account.tsx, clients/mobile/src/utility/deviceRegistration.ts, clients/mobile/src/utility/validator.ts
Fixes #HOTFIX
Device registration API will be called if any screen are in focus unless token locally found 
Please assess risk & follow up on …
=> Device registration API will be called if any screen are in focus unless token locally found 

.github/workflows/eas-mobile.yml, clients/mobile/Makefile, clients/mobile/app.json, clients/mobile/package.json, core/application/bloodDonationWorkflow/BloodDonationService.ts, core/services/aws/bloodDonation/updateBloodDonation.ts, core/services/aws/donorSearch/donorSearch.ts, iac/terraform/aws/dashboard/dashboard.tf, iac/terraform/aws/dashboard/variables.tf, iac/terraform/aws/modules.tf, iac/terraform/aws/user/outputs.tf
=> I-#480: fixed prod issues

core/application/bloodDonationWorkflow/AcceptDonationRequestService.ts, core/application/tests/bloodDonationWorkflow/BloodDonationService.test.ts, core/services/aws/bloodDonation/updateBloodDonation.ts, core/services/aws/tests/bloodDonation/updateBloodDonation.test.ts
=> I-#480: fixed unittest issues

.github/workflows/deploy-prod.yml
=> fix prod pipeline git pull

.github/workflows/deploy-prod.yml
=> fix prod pipeline issue

core/application/bloodDonationWorkflow/DonorSearchService.ts, core/application/bloodDonationWorkflow/Types.ts, core/services/aws/donorSearch/donationRequestInitiator.ts
=> NO-TICKET: fixed donation request eventName issue

core/services/aws/donorSearch/donorSearch.ts, openapi/integration/aws/donations/vtl/responseTemplates/get-posts.vtl
Fixes #
Minor code improvements
Resolves #
Please assess risk & …
=> Code improvements

iac/terraform/aws/monitoring-site/lambdas.tf
=> NO-TICKET: fixed monitor bucket env name

iac/terraform/aws/eventbridge/eventbridge.tf
=> NO-TICKET: fix event bridge max record age issue

openapi/integration/aws/donations/vtl/responseTemplates/get-posts.vtl
=> NO-TICKET: fix get posts api

clients/mobile/src/setup/navigation/Navigator.tsx
Fixes #No Ticket
This code create bug when the internet's off. So removing it as we don't need it anymore.
Please assess risk & follow up on …
=> I-#No-Ticket-removed country availability check code as we go global

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/enhancement_request.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md
Fixes #No-Ticket
Current issue templates are too detailed and take lot of information. In this PR we're trying to simplify those.
Please assess …
=> I-#No-Ticket-simplified github issue templates

clients/monitoring/src/pages/Home.tsx, clients/monitoring/src/queries/Requests/index.ts
- Flip start and end time
- Fixes #
- Resolves #
=> fix(NO-TICKET): fix incorrect start and end time

clients/monitoring/src/pages/Home.tsx
- FIx searchParms issue
- Fixes #
- Resolves #
=> fix(NO-TICKET): fix searchParams not updating

.github/workflows/ci-checks.yml, clients/monitoring/src/components/GeohashMap.tsx, clients/monitoring/src/pages/Home.tsx
- Improves react performance
- Adds distance
- Fixes #
- Resolves #
=> Improves monitor performance and visuals

.eslintrc.json, clients/mobile/Makefile, clients/mobile/src/authentication/otp/hooks/useOtp.ts, clients/mobile/src/components/NetInfoModal.tsx, clients/mobile/src/donationWorkflow/donationPosts/DonationPosts.tsx, clients/mobile/src/donationWorkflow/donationPosts/donorResponse/UI/ResponseDonationRequest.tsx, clients/mobile/src/myActivity/MyActivityTab.tsx, clients/mobile/src/myActivity/donorTracking/bloodRequestStatus/RequestStatusScreen.tsx, clients/mobile/src/myActivity/useMyActivity.ts, clients/mobile/src/setup/navigation/Navigator.tsx, clients/mobile/src/setup/notification/scheduleNotification.ts, clients/mobile/src/userWorkflow/account/UI/Account.tsx, clients/mobile/src/userWorkflow/personalInfo/UI/AddPersonalInfo.tsx, clients/mobile/src/utility/WithDeviceRegistration.tsx, clients/mobile/src/utility/deviceRegistration.ts, clients/monitoring/src/App.tsx, clients/monitoring/src/components/GeohashMap.tsx, clients/monitoring/src/components/Requests/RequestCard.tsx, clients/monitoring/src/components/Requests/RequestList.tsx, clients/monitoring/src/pages/Home.tsx, clients/monitoring/src/queries/Requests/index.ts, clients/organization/src/presentation/router/protectedRoutes.tsx, core/services/aws/bloodDonation/createBloodDonation.ts, core/services/aws/bloodDonation/updateBloodDonation.ts, core/services/aws/donorSearch/donorSearch.ts, core/services/aws/user/cognitoTrigger/lambdas/customMessageTrigger.ts
Fixes #
- Moved device registration into a wrapper component
Resolves #
- Stricter lint rules
Please assess risk & follow up on deployment of …
=> NO-TICKET: create notification device register wrapper

core/application/userWorkflow/Types.ts, core/application/userWorkflow/UserService.ts, core/services/aws/tests/user/updateUser.test.ts, core/services/aws/user/createUser.ts, core/services/aws/user/updateUser.ts
updated update user to make fields optional
- Fixes #
- Resolves #
=> I-#512: made update user fields optional

clients/monitoring/src/pages/Home.tsx
- There was an issue with react router search params, this pr hopefully resolves it
- Fixes #
- Resolves #
=> fix(NO-TICKET): fix the monitor params not persisting

clients/mobile/src/userWorkflow/context/UserProfileContext.tsx, clients/mobile/src/userWorkflow/editUserProfile/hooks/useEditProfile.ts, clients/mobile/src/userWorkflow/services/userProfileService.ts, clients/mobile/src/userWorkflow/userProfile/UI/Profile.tsx, clients/mobile/src/utility/validator.ts
Bugfix: When pressing the available for donation toggle in edit screen it re render the screen and take the initial route params value as source the reset the toggle button value which was fixed in this PR 
- Fixes #No-Ticket
- Resolves #
=> I-#No-Ticket-available for donation toggle bug fix

.devcontainer/devcontainer.json, .github/workflows/build-mobile.yml, .github/workflows/eas-mobile.yml, Dockerfile, Makefile, clients/mobile/.gitignore, clients/mobile/Makefile, clients/mobile/package.json, docs/development/MobileAppDevelopment.rst, package-lock.json
=> feat(NO-TICKET): add local build

deployment/aws/terraform/provider.tf
=> NO-TICKET: add tags to all resource

deployment/aws/terraform/provider.tf
=> NO-TICKET: add tags to default provider
